// Generated by https://quicktype.io

export interface UserModel {
    collectionId:   string;
    collectionName: string;
    created:        string;
    id:             string;
    password:       string;
    updated:        string;
    username:       string;
}
